-- 1. ADIM: Şema Oluşturma
CREATE SCHEMA IF NOT EXISTS "library-management";

-- 2. ADIM: Fonksiyonları Oluşturma (Triggerlar hata vermesin diye önce bunlar tanımlanmalı)
CREATE OR REPLACE FUNCTION "library-management".update_book_comment_count()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF (TG_OP = 'INSERT') THEN
UPDATE "library-management".book
SET comment_count = COALESCE(comment_count, 0) + 1
WHERE id = NEW.book_id;
RETURN NEW;
ELSIF (TG_OP = 'DELETE') THEN
UPDATE "library-management".book
SET comment_count = GREATEST(COALESCE(comment_count, 0) - 1, 0)
WHERE id = OLD.book_id;
RETURN OLD;
END IF;
RETURN NULL;
END;
$function$;

CREATE OR REPLACE FUNCTION "library-management".update_book_like_count()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF (TG_OP = 'INSERT') THEN
UPDATE "library-management".book
SET like_count = COALESCE(like_count, 0) + 1
WHERE id = NEW.book_id;
RETURN NEW;
ELSIF (TG_OP = 'DELETE') THEN
UPDATE "library-management".book
SET like_count = GREATEST(COALESCE(like_count, 0) - 1, 0)
WHERE id = OLD.book_id;
RETURN OLD;
END IF;
RETURN NULL;
END;
$function$;

-- 3. ADIM: Sequence (Sıralayıcı) Oluşturma
CREATE SEQUENCE IF NOT EXISTS "library-management".author_id_seq INCREMENT BY 1 MINVALUE 1 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS "library-management".book_id_seq INCREMENT BY 1 MINVALUE 1 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS "library-management".book_likes_id_seq INCREMENT BY 1 MINVALUE 1 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS "library-management".borrowing_id_seq INCREMENT BY 1 MINVALUE 1 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS "library-management".category_id_seq INCREMENT BY 1 MINVALUE 1 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS "library-management".comments_id_seq INCREMENT BY 1 MINVALUE 1 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS "library-management".penalty_id_seq INCREMENT BY 1 MINVALUE 1 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS "library-management".refresh_token_id_seq INCREMENT BY 1 MINVALUE 1 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS "library-management".user_id_seq INCREMENT BY 1 MINVALUE 1 START 1 CACHE 1 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS "library-management".verification_token_seq INCREMENT BY 50 MINVALUE 1 START 1 CACHE 1 NO CYCLE;

-- 4. ADIM: Tabloları Oluşturma

CREATE TABLE IF NOT EXISTS "library-management".author (
                                                           create_time timestamp(6) NULL,
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    first_name varchar(255) NULL,
    last_name varchar(255) NULL,
    CONSTRAINT author_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS "library-management".book (
                                                         number_of_pages int4 NULL,
                                                         create_time timestamp(6) NULL,
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    isbn int8 NULL,
    image_url varchar(255) NULL,
    situation varchar(255) NULL,
    title varchar(255) NULL,
    like_count int8 NULL,
    comment_count int8 DEFAULT 0 NOT NULL,
    CONSTRAINT book_isbn_key UNIQUE (isbn),
    CONSTRAINT book_pkey PRIMARY KEY (id),
    CONSTRAINT book_situation_check CHECK (((situation)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'BORROWED'::character varying, 'DELETED'::character varying])::text[])))
    );

CREATE TABLE IF NOT EXISTS "library-management".category (
                                                             create_time timestamp(6) NULL,
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    category_name varchar(255) NULL,
    CONSTRAINT category_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS "library-management"."user" (
                                                           verified bool NULL,
                                                           create_time timestamp(6) NULL,
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    email varchar(255) NULL,
    "password" varchar(255) NULL,
    username varchar(255) NULL,
    CONSTRAINT user_email_key UNIQUE (email),
    CONSTRAINT user_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS "library-management".penalty (
                                                            amount float8 NULL,
                                                            state_of_penalty int2 NULL,
                                                            borrowing_id int8 NULL,
                                                            create_time timestamp(6) NULL,
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    user_id int8 NULL,
    CONSTRAINT penalty_pkey PRIMARY KEY (id),
    CONSTRAINT penalty_state_of_penalty_check CHECK (((state_of_penalty >= 0) AND (state_of_penalty <= 1)))
    );

CREATE TABLE IF NOT EXISTS "library-management".book_authors (
                                                                 authors_id int8 NOT NULL,
                                                                 book_id int8 NOT NULL,
                                                                 CONSTRAINT book_authors_pkey PRIMARY KEY (authors_id, book_id),
    CONSTRAINT fk551i3sllw1wj7ex6nir16blsm FOREIGN KEY (authors_id) REFERENCES "library-management".author(id),
    CONSTRAINT fks4xm7q8i3uxvaiswj1c35nnxw FOREIGN KEY (book_id) REFERENCES "library-management".book(id)
    );

CREATE TABLE IF NOT EXISTS "library-management".book_categories (
                                                                    book_id int8 NOT NULL,
                                                                    categories_id int8 NOT NULL,
                                                                    CONSTRAINT book_categories_pkey PRIMARY KEY (book_id, categories_id),
    CONSTRAINT fkcua8hutsmi5x4wx20sdlptj9w FOREIGN KEY (categories_id) REFERENCES "library-management".category(id),
    CONSTRAINT fkrq5mftm1ejl023epqbn42lpa3 FOREIGN KEY (book_id) REFERENCES "library-management".book(id)
    );

CREATE TABLE IF NOT EXISTS "library-management".book_likes (
                                                               id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    liked_at timestamp(6) NULL,
    book_id int8 NOT NULL,
    user_id int8 NOT NULL,
    CONSTRAINT book_likes_pkey PRIMARY KEY (id),
    CONSTRAINT uk6remv0i7vg55grhex7j7x9bet UNIQUE (user_id, book_id),
    CONSTRAINT fkd1fr8u2wbdqsa7y43ipndot9v FOREIGN KEY (book_id) REFERENCES "library-management".book(id),
    CONSTRAINT fkh23fy9hmm7t01kv961w6fx5cs FOREIGN KEY (user_id) REFERENCES "library-management"."user"(id)
    );

CREATE TABLE IF NOT EXISTS "library-management".borrowing (
                                                              book_id int8 NULL,
                                                              borrowed_date timestamp(6) NULL,
    create_time timestamp(6) NULL,
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    last_return_date timestamp(6) NULL,
    return_date timestamp(6) NULL,
    user_id int8 NULL,
    CONSTRAINT borrowing_pkey PRIMARY KEY (id),
    CONSTRAINT fkeu12r38wvjgkybkcnyb09j3f5 FOREIGN KEY (user_id) REFERENCES "library-management"."user"(id),
    CONSTRAINT fkpgw9do56tnua1aepwswrbwifh FOREIGN KEY (book_id) REFERENCES "library-management".book(id)
    );

CREATE TABLE IF NOT EXISTS "library-management"."comments" (
                                                               id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    "content" text NOT NULL,
    create_time timestamp(6) NULL,
    book_id int8 NOT NULL,
    user_id int8 NOT NULL,
    deleted bool NULL,
    CONSTRAINT comments_pkey PRIMARY KEY (id),
    CONSTRAINT fkca972s36glonobtd1w60h77by FOREIGN KEY (book_id) REFERENCES "library-management".book(id),
    CONSTRAINT fkqi14bvepnwtjbbaxm7m4v44yg FOREIGN KEY (user_id) REFERENCES "library-management"."user"(id)
    );

CREATE TABLE IF NOT EXISTS "library-management".refresh_token (
                                                                  create_time timestamp(6) NULL,
    expired_date timestamp(6) NULL,
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    user_id int8 NULL,
    refresh_token varchar(255) NULL,
    CONSTRAINT refresh_token_pkey PRIMARY KEY (id),
    CONSTRAINT fkfgk1klcib7i15utalmcqo7krt FOREIGN KEY (user_id) REFERENCES "library-management"."user"(id)
    );

CREATE TABLE IF NOT EXISTS "library-management".user_roles (
                                                               user_id int8 NOT NULL,
                                                               "role" varchar(255) NULL,
    CONSTRAINT user_roles_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[]))),
    CONSTRAINT fk55itppkw3i07do3h7qoclqd4k FOREIGN KEY (user_id) REFERENCES "library-management"."user"(id)
    );

CREATE TABLE IF NOT EXISTS "library-management".verification_token (
                                                                       expiry_date timestamp(6) NULL,
    id int8 NOT NULL,
    user_id int8 NULL,
    "token" varchar(255) NULL,
    CONSTRAINT verification_token_pkey PRIMARY KEY (id),
    CONSTRAINT verification_token_user_id_key UNIQUE (user_id),
    CONSTRAINT fkrdn0mss276m9jdobfhhn2qogw FOREIGN KEY (user_id) REFERENCES "library-management"."user"(id)
    );

-- 5. ADIM: Triggerları Bağlama (Çakışma olmaması için önce Drop kontrolü yapılır)

DROP TRIGGER IF EXISTS trg_update_like_count ON "library-management".book_likes;
CREATE TRIGGER trg_update_like_count
    AFTER INSERT OR DELETE ON "library-management".book_likes
    FOR EACH ROW EXECUTE FUNCTION "library-management".update_book_like_count();

DROP TRIGGER IF EXISTS trg_update_comment_count ON "library-management".comments;
CREATE TRIGGER trg_update_comment_count
    AFTER INSERT OR DELETE ON "library-management".comments
    FOR EACH ROW EXECUTE FUNCTION "library-management".update_book_comment_count();